// KV commands as they ride the raft log, and the cached responses that
// live in the replicated session table (and therefore in snapshots).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/quorumpb/kv.proto

package quorumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_UNSPECIFIED OpType = 0
	OpType_OP_REGISTER    OpType = 1 // create a session; ClientID = the entry's log index
	OpType_OP_PUT         OpType = 2
	OpType_OP_DELETE      OpType = 3
	OpType_OP_CAS         OpType = 4
	// OP_GET is a request-envelope op only: reads never enter the log — they
	// take the ReadIndex path.
	OpType_OP_GET OpType = 5
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_REGISTER",
		2: "OP_PUT",
		3: "OP_DELETE",
		4: "OP_CAS",
		5: "OP_GET",
	}
	OpType_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_REGISTER":    1,
		"OP_PUT":         2,
		"OP_DELETE":      3,
		"OP_CAS":         4,
		"OP_GET":         5,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quorumpb_kv_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_proto_quorumpb_kv_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_quorumpb_kv_proto_rawDescGZIP(), []int{0}
}

// Command is one replicated state-machine command. Reads (Get) never enter
// the log — they use the ReadIndex protocol.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            OpType                 `protobuf:"varint,1,opt,name=op,proto3,enum=quorumpb.OpType" json:"op,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // 0 only for OP_REGISTER
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	OldValue      string                 `protobuf:"bytes,6,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"` // OP_CAS: expected current value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_proto_quorumpb_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_kv_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_UNSPECIFIED
}

func (x *Command) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Command) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Command) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Command) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Command) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

// Result is a command's outcome, cached per-session for dedup. It is part
// of replicated state: restore a snapshot without it and dedup silently
// breaks.
type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // OP_REGISTER: unused; reads use it outside the log
	CasOk         bool                   `protobuf:"varint,2,opt,name=cas_ok,json=casOk,proto3" json:"cas_ok,omitempty"`
	ClientId      uint64                 `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // OP_REGISTER: the assigned id
	Err           uint32                 `protobuf:"varint,4,opt,name=err,proto3" json:"err,omitempty"`                           // kv.Err* codes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_proto_quorumpb_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_kv_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Result) GetCasOk() bool {
	if x != nil {
		return x.CasOk
	}
	return false
}

func (x *Result) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Result) GetErr() uint32 {
	if x != nil {
		return x.Err
	}
	return 0
}

// SessionRec is one session's dedup state.
type SessionRec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSeq       uint64                 `protobuf:"varint,1,opt,name=last_seq,json=lastSeq,proto3" json:"last_seq,omitempty"`
	Cached        *Result                `protobuf:"bytes,2,opt,name=cached,proto3" json:"cached,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRec) Reset() {
	*x = SessionRec{}
	mi := &file_proto_quorumpb_kv_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRec) ProtoMessage() {}

func (x *SessionRec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_kv_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRec.ProtoReflect.Descriptor instead.
func (*SessionRec) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_kv_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRec) GetLastSeq() uint64 {
	if x != nil {
		return x.LastSeq
	}
	return 0
}

func (x *SessionRec) GetCached() *Result {
	if x != nil {
		return x.Cached
	}
	return nil
}

// KVSnapshot is the serialized state machine: the store AND the session
// table — sessions are replicated state; restore one without the other and
// dedup silently breaks.
type KVSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]string      `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sessions      map[uint64]*SessionRec `protobuf:"bytes,2,rep,name=sessions,proto3" json:"sessions,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVSnapshot) Reset() {
	*x = KVSnapshot{}
	mi := &file_proto_quorumpb_kv_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVSnapshot) ProtoMessage() {}

func (x *KVSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_kv_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVSnapshot.ProtoReflect.Descriptor instead.
func (*KVSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_kv_proto_rawDescGZIP(), []int{3}
}

func (x *KVSnapshot) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KVSnapshot) GetSessions() map[uint64]*SessionRec {
	if x != nil {
		return x.Sessions
	}
	return nil
}

var File_proto_quorumpb_kv_proto protoreflect.FileDescriptor

const file_proto_quorumpb_kv_proto_rawDesc = "" +
	"\n" +
	"\x17proto/quorumpb/kv.proto\x12\bquorumpb\"\x9f\x01\n" +
	"\aCommand\x12 \n" +
	"\x02op\x18\x01 \x01(\x0e2\x10.quorumpb.OpTypeR\x02op\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x1b\n" +
	"\told_value\x18\x06 \x01(\tR\boldValue\"d\n" +
	"\x06Result\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x15\n" +
	"\x06cas_ok\x18\x02 \x01(\bR\x05casOk\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x04R\bclientId\x12\x10\n" +
	"\x03err\x18\x04 \x01(\rR\x03err\"Q\n" +
	"\n" +
	"SessionRec\x12\x19\n" +
	"\blast_seq\x18\x01 \x01(\x04R\alastSeq\x12(\n" +
	"\x06cached\x18\x02 \x01(\v2\x10.quorumpb.ResultR\x06cached\"\x8c\x02\n" +
	"\n" +
	"KVSnapshot\x122\n" +
	"\x04data\x18\x01 \x03(\v2\x1e.quorumpb.KVSnapshot.DataEntryR\x04data\x12>\n" +
	"\bsessions\x18\x02 \x03(\v2\".quorumpb.KVSnapshot.SessionsEntryR\bsessions\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aQ\n" +
	"\rSessionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.quorumpb.SessionRecR\x05value:\x028\x01*`\n" +
	"\x06OpType\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vOP_REGISTER\x10\x01\x12\n" +
	"\n" +
	"\x06OP_PUT\x10\x02\x12\r\n" +
	"\tOP_DELETE\x10\x03\x12\n" +
	"\n" +
	"\x06OP_CAS\x10\x04\x12\n" +
	"\n" +
	"\x06OP_GET\x10\x05B-Z+github.com/Dario-Zela/quorum/proto/quorumpbb\x06proto3"

var (
	file_proto_quorumpb_kv_proto_rawDescOnce sync.Once
	file_proto_quorumpb_kv_proto_rawDescData []byte
)

func file_proto_quorumpb_kv_proto_rawDescGZIP() []byte {
	file_proto_quorumpb_kv_proto_rawDescOnce.Do(func() {
		file_proto_quorumpb_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quorumpb_kv_proto_rawDesc), len(file_proto_quorumpb_kv_proto_rawDesc)))
	})
	return file_proto_quorumpb_kv_proto_rawDescData
}

var file_proto_quorumpb_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_quorumpb_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_quorumpb_kv_proto_goTypes = []any{
	(OpType)(0),        // 0: quorumpb.OpType
	(*Command)(nil),    // 1: quorumpb.Command
	(*Result)(nil),     // 2: quorumpb.Result
	(*SessionRec)(nil), // 3: quorumpb.SessionRec
	(*KVSnapshot)(nil), // 4: quorumpb.KVSnapshot
	nil,                // 5: quorumpb.KVSnapshot.DataEntry
	nil,                // 6: quorumpb.KVSnapshot.SessionsEntry
}
var file_proto_quorumpb_kv_proto_depIdxs = []int32{
	0, // 0: quorumpb.Command.op:type_name -> quorumpb.OpType
	2, // 1: quorumpb.SessionRec.cached:type_name -> quorumpb.Result
	5, // 2: quorumpb.KVSnapshot.data:type_name -> quorumpb.KVSnapshot.DataEntry
	6, // 3: quorumpb.KVSnapshot.sessions:type_name -> quorumpb.KVSnapshot.SessionsEntry
	3, // 4: quorumpb.KVSnapshot.SessionsEntry.value:type_name -> quorumpb.SessionRec
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_quorumpb_kv_proto_init() }
func file_proto_quorumpb_kv_proto_init() {
	if File_proto_quorumpb_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quorumpb_kv_proto_rawDesc), len(file_proto_quorumpb_kv_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_quorumpb_kv_proto_goTypes,
		DependencyIndexes: file_proto_quorumpb_kv_proto_depIdxs,
		EnumInfos:         file_proto_quorumpb_kv_proto_enumTypes,
		MessageInfos:      file_proto_quorumpb_kv_proto_msgTypes,
	}.Build()
	File_proto_quorumpb_kv_proto = out.File
	file_proto_quorumpb_kv_proto_goTypes = nil
	file_proto_quorumpb_kv_proto_depIdxs = nil
}
