// Wire protocol: raft message envelopes between peers, and the client-facing
// KV + status services.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/quorumpb/rpc.proto

package quorumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoStatus int32

const (
	DoStatus_DO_OK DoStatus = 0
	// Not the leader; leader_hint may name one. Retry there.
	DoStatus_DO_NOT_LEADER DoStatus = 1
	// Leadership was lost with the op in flight; it MAY still commit.
	// Retry with the SAME seq — dedup collapses it.
	DoStatus_DO_RETRY DoStatus = 2
)

// Enum value maps for DoStatus.
var (
	DoStatus_name = map[int32]string{
		0: "DO_OK",
		1: "DO_NOT_LEADER",
		2: "DO_RETRY",
	}
	DoStatus_value = map[string]int32{
		"DO_OK":         0,
		"DO_NOT_LEADER": 1,
		"DO_RETRY":      2,
	}
)

func (x DoStatus) Enum() *DoStatus {
	p := new(DoStatus)
	*p = x
	return p
}

func (x DoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_quorumpb_rpc_proto_enumTypes[0].Descriptor()
}

func (DoStatus) Type() protoreflect.EnumType {
	return &file_proto_quorumpb_rpc_proto_enumTypes[0]
}

func (x DoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DoStatus.Descriptor instead.
func (DoStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{0}
}

// Envelope carries one raft message. Transport is fire-and-forget one-way
// streams: replies are separate envelopes on the peer's own outbound
// stream, mirroring the core's message-passing model.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	From  uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_RequestVote
	//	*Envelope_RequestVoteReply
	//	*Envelope_AppendEntries
	//	*Envelope_AppendEntriesReply
	//	*Envelope_InstallSnapshot
	//	*Envelope_InstallSnapshotReply
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetRequestVote() *RequestVoteMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_RequestVote); ok {
			return x.RequestVote
		}
	}
	return nil
}

func (x *Envelope) GetRequestVoteReply() *RequestVoteReplyMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_RequestVoteReply); ok {
			return x.RequestVoteReply
		}
	}
	return nil
}

func (x *Envelope) GetAppendEntries() *AppendEntriesMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_AppendEntries); ok {
			return x.AppendEntries
		}
	}
	return nil
}

func (x *Envelope) GetAppendEntriesReply() *AppendEntriesReplyMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_AppendEntriesReply); ok {
			return x.AppendEntriesReply
		}
	}
	return nil
}

func (x *Envelope) GetInstallSnapshot() *InstallSnapshotMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_InstallSnapshot); ok {
			return x.InstallSnapshot
		}
	}
	return nil
}

func (x *Envelope) GetInstallSnapshotReply() *InstallSnapshotReplyMsg {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_InstallSnapshotReply); ok {
			return x.InstallSnapshotReply
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_RequestVote struct {
	RequestVote *RequestVoteMsg `protobuf:"bytes,2,opt,name=request_vote,json=requestVote,proto3,oneof"`
}

type Envelope_RequestVoteReply struct {
	RequestVoteReply *RequestVoteReplyMsg `protobuf:"bytes,3,opt,name=request_vote_reply,json=requestVoteReply,proto3,oneof"`
}

type Envelope_AppendEntries struct {
	AppendEntries *AppendEntriesMsg `protobuf:"bytes,4,opt,name=append_entries,json=appendEntries,proto3,oneof"`
}

type Envelope_AppendEntriesReply struct {
	AppendEntriesReply *AppendEntriesReplyMsg `protobuf:"bytes,5,opt,name=append_entries_reply,json=appendEntriesReply,proto3,oneof"`
}

type Envelope_InstallSnapshot struct {
	InstallSnapshot *InstallSnapshotMsg `protobuf:"bytes,6,opt,name=install_snapshot,json=installSnapshot,proto3,oneof"`
}

type Envelope_InstallSnapshotReply struct {
	InstallSnapshotReply *InstallSnapshotReplyMsg `protobuf:"bytes,7,opt,name=install_snapshot_reply,json=installSnapshotReply,proto3,oneof"`
}

func (*Envelope_RequestVote) isEnvelope_Msg() {}

func (*Envelope_RequestVoteReply) isEnvelope_Msg() {}

func (*Envelope_AppendEntries) isEnvelope_Msg() {}

func (*Envelope_AppendEntriesReply) isEnvelope_Msg() {}

func (*Envelope_InstallSnapshot) isEnvelope_Msg() {}

func (*Envelope_InstallSnapshotReply) isEnvelope_Msg() {}

type InstallSnapshotMsg struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Term              uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId          uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LastIncludedIndex uint64                 `protobuf:"varint,3,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,4,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Data              []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotMsg) Reset() {
	*x = InstallSnapshotMsg{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotMsg) ProtoMessage() {}

func (x *InstallSnapshotMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotMsg.ProtoReflect.Descriptor instead.
func (*InstallSnapshotMsg) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *InstallSnapshotMsg) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotMsg) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotMsg) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotMsg) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type InstallSnapshotReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	MatchIndex    uint64                 `protobuf:"varint,2,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotReplyMsg) Reset() {
	*x = InstallSnapshotReplyMsg{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotReplyMsg) ProtoMessage() {}

func (x *InstallSnapshotReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotReplyMsg.ProtoReflect.Descriptor instead.
func (*InstallSnapshotReplyMsg) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *InstallSnapshotReplyMsg) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *InstallSnapshotReplyMsg) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

type RequestVoteMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   uint64                 `protobuf:"varint,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	LastLogIndex  uint64                 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex,proto3" json:"last_log_index,omitempty"`
	LastLogTerm   uint64                 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm,proto3" json:"last_log_term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteMsg) Reset() {
	*x = RequestVoteMsg{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteMsg) ProtoMessage() {}

func (x *RequestVoteMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteMsg.ProtoReflect.Descriptor instead.
func (*RequestVoteMsg) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteMsg) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteMsg) GetCandidateId() uint64 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *RequestVoteMsg) GetLastLogIndex() uint64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteMsg) GetLastLogTerm() uint64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Granted       bool                   `protobuf:"varint,2,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReplyMsg) Reset() {
	*x = RequestVoteReplyMsg{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReplyMsg) ProtoMessage() {}

func (x *RequestVoteReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReplyMsg.ProtoReflect.Descriptor instead.
func (*RequestVoteReplyMsg) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteReplyMsg) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReplyMsg) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type AppendEntriesMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      uint64                 `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	PrevLogIndex  uint64                 `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex,proto3" json:"prev_log_index,omitempty"`
	PrevLogTerm   uint64                 `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm,proto3" json:"prev_log_term,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  uint64                 `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit,proto3" json:"leader_commit,omitempty"`
	Round         uint64                 `protobuf:"varint,7,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesMsg) Reset() {
	*x = AppendEntriesMsg{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesMsg) ProtoMessage() {}

func (x *AppendEntriesMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesMsg.ProtoReflect.Descriptor instead.
func (*AppendEntriesMsg) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *AppendEntriesMsg) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesMsg) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *AppendEntriesMsg) GetPrevLogIndex() uint64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesMsg) GetPrevLogTerm() uint64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesMsg) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesMsg) GetLeaderCommit() uint64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

func (x *AppendEntriesMsg) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type AppendEntriesReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	MatchIndex    uint64                 `protobuf:"varint,3,opt,name=match_index,json=matchIndex,proto3" json:"match_index,omitempty"`
	ConflictIndex uint64                 `protobuf:"varint,4,opt,name=conflict_index,json=conflictIndex,proto3" json:"conflict_index,omitempty"`
	ConflictTerm  uint64                 `protobuf:"varint,5,opt,name=conflict_term,json=conflictTerm,proto3" json:"conflict_term,omitempty"`
	Round         uint64                 `protobuf:"varint,6,opt,name=round,proto3" json:"round,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReplyMsg) Reset() {
	*x = AppendEntriesReplyMsg{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReplyMsg) ProtoMessage() {}

func (x *AppendEntriesReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReplyMsg.ProtoReflect.Descriptor instead.
func (*AppendEntriesReplyMsg) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *AppendEntriesReplyMsg) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReplyMsg) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesReplyMsg) GetMatchIndex() uint64 {
	if x != nil {
		return x.MatchIndex
	}
	return 0
}

func (x *AppendEntriesReplyMsg) GetConflictIndex() uint64 {
	if x != nil {
		return x.ConflictIndex
	}
	return 0
}

func (x *AppendEntriesReplyMsg) GetConflictTerm() uint64 {
	if x != nil {
		return x.ConflictTerm
	}
	return 0
}

func (x *AppendEntriesReplyMsg) GetRound() uint64 {
	if x != nil {
		return x.Round
	}
	return 0
}

type DeliverAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverAck) Reset() {
	*x = DeliverAck{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverAck) ProtoMessage() {}

func (x *DeliverAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverAck.ProtoReflect.Descriptor instead.
func (*DeliverAck) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{7}
}

type DoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Cmd   *Command               `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	// stale_read serves OP_GET from local state with no protocol — any node,
	// no linearizability. Offered for the benchmark contrast table.
	StaleRead     bool `protobuf:"varint,2,opt,name=stale_read,json=staleRead,proto3" json:"stale_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRequest) Reset() {
	*x = DoRequest{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRequest) ProtoMessage() {}

func (x *DoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRequest.ProtoReflect.Descriptor instead.
func (*DoRequest) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{8}
}

func (x *DoRequest) GetCmd() *Command {
	if x != nil {
		return x.Cmd
	}
	return nil
}

func (x *DoRequest) GetStaleRead() bool {
	if x != nil {
		return x.StaleRead
	}
	return false
}

type DoReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *Result                `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Status        DoStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=quorumpb.DoStatus" json:"status,omitempty"`
	LeaderHint    uint64                 `protobuf:"varint,3,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoReply) Reset() {
	*x = DoReply{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoReply) ProtoMessage() {}

func (x *DoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoReply.ProtoReflect.Descriptor instead.
func (*DoReply) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{9}
}

func (x *DoReply) GetResult() *Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *DoReply) GetStatus() DoStatus {
	if x != nil {
		return x.Status
	}
	return DoStatus_DO_OK
}

func (x *DoReply) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{10}
}

type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Term          uint64                 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	CommitIndex   uint64                 `protobuf:"varint,4,opt,name=commit_index,json=commitIndex,proto3" json:"commit_index,omitempty"`
	LastApplied   uint64                 `protobuf:"varint,5,opt,name=last_applied,json=lastApplied,proto3" json:"last_applied,omitempty"`
	LastIndex     uint64                 `protobuf:"varint,6,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	LeaderHint    uint64                 `protobuf:"varint,7,opt,name=leader_hint,json=leaderHint,proto3" json:"leader_hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_rpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_rpc_proto_rawDescGZIP(), []int{11}
}

func (x *StatusReply) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StatusReply) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StatusReply) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusReply) GetCommitIndex() uint64 {
	if x != nil {
		return x.CommitIndex
	}
	return 0
}

func (x *StatusReply) GetLastApplied() uint64 {
	if x != nil {
		return x.LastApplied
	}
	return 0
}

func (x *StatusReply) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

func (x *StatusReply) GetLeaderHint() uint64 {
	if x != nil {
		return x.LeaderHint
	}
	return 0
}

var File_proto_quorumpb_rpc_proto protoreflect.FileDescriptor

const file_proto_quorumpb_rpc_proto_rawDesc = "" +
	"\n" +
	"\x18proto/quorumpb/rpc.proto\x12\bquorumpb\x1a\x17proto/quorumpb/kv.proto\x1a\x18proto/quorumpb/wal.proto\"\xf3\x03\n" +
	"\bEnvelope\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12=\n" +
	"\frequest_vote\x18\x02 \x01(\v2\x18.quorumpb.RequestVoteMsgH\x00R\vrequestVote\x12M\n" +
	"\x12request_vote_reply\x18\x03 \x01(\v2\x1d.quorumpb.RequestVoteReplyMsgH\x00R\x10requestVoteReply\x12C\n" +
	"\x0eappend_entries\x18\x04 \x01(\v2\x1a.quorumpb.AppendEntriesMsgH\x00R\rappendEntries\x12S\n" +
	"\x14append_entries_reply\x18\x05 \x01(\v2\x1f.quorumpb.AppendEntriesReplyMsgH\x00R\x12appendEntriesReply\x12I\n" +
	"\x10install_snapshot\x18\x06 \x01(\v2\x1c.quorumpb.InstallSnapshotMsgH\x00R\x0finstallSnapshot\x12Y\n" +
	"\x16install_snapshot_reply\x18\a \x01(\v2!.quorumpb.InstallSnapshotReplyMsgH\x00R\x14installSnapshotReplyB\x05\n" +
	"\x03msg\"\xb7\x01\n" +
	"\x12InstallSnapshotMsg\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12.\n" +
	"\x13last_included_index\x18\x03 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x04 \x01(\x04R\x10lastIncludedTerm\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\"N\n" +
	"\x17InstallSnapshotReplyMsg\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1f\n" +
	"\vmatch_index\x18\x02 \x01(\x04R\n" +
	"matchIndex\"\x91\x01\n" +
	"\x0eRequestVoteMsg\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\x04R\vcandidateId\x12$\n" +
	"\x0elast_log_index\x18\x03 \x01(\x04R\flastLogIndex\x12\"\n" +
	"\rlast_log_term\x18\x04 \x01(\x04R\vlastLogTerm\"C\n" +
	"\x13RequestVoteReplyMsg\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\agranted\x18\x02 \x01(\bR\agranted\"\xf3\x01\n" +
	"\x10AppendEntriesMsg\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x04R\bleaderId\x12$\n" +
	"\x0eprev_log_index\x18\x03 \x01(\x04R\fprevLogIndex\x12\"\n" +
	"\rprev_log_term\x18\x04 \x01(\x04R\vprevLogTerm\x12)\n" +
	"\aentries\x18\x05 \x03(\v2\x0f.quorumpb.EntryR\aentries\x12#\n" +
	"\rleader_commit\x18\x06 \x01(\x04R\fleaderCommit\x12\x14\n" +
	"\x05round\x18\a \x01(\x04R\x05round\"\xc8\x01\n" +
	"\x15AppendEntriesReplyMsg\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vmatch_index\x18\x03 \x01(\x04R\n" +
	"matchIndex\x12%\n" +
	"\x0econflict_index\x18\x04 \x01(\x04R\rconflictIndex\x12#\n" +
	"\rconflict_term\x18\x05 \x01(\x04R\fconflictTerm\x12\x14\n" +
	"\x05round\x18\x06 \x01(\x04R\x05round\"\f\n" +
	"\n" +
	"DeliverAck\"O\n" +
	"\tDoRequest\x12#\n" +
	"\x03cmd\x18\x01 \x01(\v2\x11.quorumpb.CommandR\x03cmd\x12\x1d\n" +
	"\n" +
	"stale_read\x18\x02 \x01(\bR\tstaleRead\"\x80\x01\n" +
	"\aDoReply\x12(\n" +
	"\x06result\x18\x01 \x01(\v2\x10.quorumpb.ResultR\x06result\x12*\n" +
	"\x06status\x18\x02 \x01(\x0e2\x12.quorumpb.DoStatusR\x06status\x12\x1f\n" +
	"\vleader_hint\x18\x03 \x01(\x04R\n" +
	"leaderHint\"\x0f\n" +
	"\rStatusRequest\"\xcb\x01\n" +
	"\vStatusReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04term\x18\x03 \x01(\x04R\x04term\x12!\n" +
	"\fcommit_index\x18\x04 \x01(\x04R\vcommitIndex\x12!\n" +
	"\flast_applied\x18\x05 \x01(\x04R\vlastApplied\x12\x1d\n" +
	"\n" +
	"last_index\x18\x06 \x01(\x04R\tlastIndex\x12\x1f\n" +
	"\vleader_hint\x18\a \x01(\x04R\n" +
	"leaderHint*6\n" +
	"\bDoStatus\x12\t\n" +
	"\x05DO_OK\x10\x00\x12\x11\n" +
	"\rDO_NOT_LEADER\x10\x01\x12\f\n" +
	"\bDO_RETRY\x10\x022F\n" +
	"\rRaftTransport\x125\n" +
	"\aDeliver\x12\x12.quorumpb.Envelope\x1a\x14.quorumpb.DeliverAck(\x012r\n" +
	"\bQuorumKV\x12,\n" +
	"\x02Do\x12\x13.quorumpb.DoRequest\x1a\x11.quorumpb.DoReply\x128\n" +
	"\x06Status\x12\x17.quorumpb.StatusRequest\x1a\x15.quorumpb.StatusReplyB-Z+github.com/Dario-Zela/quorum/proto/quorumpbb\x06proto3"

var (
	file_proto_quorumpb_rpc_proto_rawDescOnce sync.Once
	file_proto_quorumpb_rpc_proto_rawDescData []byte
)

func file_proto_quorumpb_rpc_proto_rawDescGZIP() []byte {
	file_proto_quorumpb_rpc_proto_rawDescOnce.Do(func() {
		file_proto_quorumpb_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quorumpb_rpc_proto_rawDesc), len(file_proto_quorumpb_rpc_proto_rawDesc)))
	})
	return file_proto_quorumpb_rpc_proto_rawDescData
}

var file_proto_quorumpb_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_quorumpb_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_quorumpb_rpc_proto_goTypes = []any{
	(DoStatus)(0),                   // 0: quorumpb.DoStatus
	(*Envelope)(nil),                // 1: quorumpb.Envelope
	(*InstallSnapshotMsg)(nil),      // 2: quorumpb.InstallSnapshotMsg
	(*InstallSnapshotReplyMsg)(nil), // 3: quorumpb.InstallSnapshotReplyMsg
	(*RequestVoteMsg)(nil),          // 4: quorumpb.RequestVoteMsg
	(*RequestVoteReplyMsg)(nil),     // 5: quorumpb.RequestVoteReplyMsg
	(*AppendEntriesMsg)(nil),        // 6: quorumpb.AppendEntriesMsg
	(*AppendEntriesReplyMsg)(nil),   // 7: quorumpb.AppendEntriesReplyMsg
	(*DeliverAck)(nil),              // 8: quorumpb.DeliverAck
	(*DoRequest)(nil),               // 9: quorumpb.DoRequest
	(*DoReply)(nil),                 // 10: quorumpb.DoReply
	(*StatusRequest)(nil),           // 11: quorumpb.StatusRequest
	(*StatusReply)(nil),             // 12: quorumpb.StatusReply
	(*Entry)(nil),                   // 13: quorumpb.Entry
	(*Command)(nil),                 // 14: quorumpb.Command
	(*Result)(nil),                  // 15: quorumpb.Result
}
var file_proto_quorumpb_rpc_proto_depIdxs = []int32{
	4,  // 0: quorumpb.Envelope.request_vote:type_name -> quorumpb.RequestVoteMsg
	5,  // 1: quorumpb.Envelope.request_vote_reply:type_name -> quorumpb.RequestVoteReplyMsg
	6,  // 2: quorumpb.Envelope.append_entries:type_name -> quorumpb.AppendEntriesMsg
	7,  // 3: quorumpb.Envelope.append_entries_reply:type_name -> quorumpb.AppendEntriesReplyMsg
	2,  // 4: quorumpb.Envelope.install_snapshot:type_name -> quorumpb.InstallSnapshotMsg
	3,  // 5: quorumpb.Envelope.install_snapshot_reply:type_name -> quorumpb.InstallSnapshotReplyMsg
	13, // 6: quorumpb.AppendEntriesMsg.entries:type_name -> quorumpb.Entry
	14, // 7: quorumpb.DoRequest.cmd:type_name -> quorumpb.Command
	15, // 8: quorumpb.DoReply.result:type_name -> quorumpb.Result
	0,  // 9: quorumpb.DoReply.status:type_name -> quorumpb.DoStatus
	1,  // 10: quorumpb.RaftTransport.Deliver:input_type -> quorumpb.Envelope
	9,  // 11: quorumpb.QuorumKV.Do:input_type -> quorumpb.DoRequest
	11, // 12: quorumpb.QuorumKV.Status:input_type -> quorumpb.StatusRequest
	8,  // 13: quorumpb.RaftTransport.Deliver:output_type -> quorumpb.DeliverAck
	10, // 14: quorumpb.QuorumKV.Do:output_type -> quorumpb.DoReply
	12, // 15: quorumpb.QuorumKV.Status:output_type -> quorumpb.StatusReply
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_quorumpb_rpc_proto_init() }
func file_proto_quorumpb_rpc_proto_init() {
	if File_proto_quorumpb_rpc_proto != nil {
		return
	}
	file_proto_quorumpb_kv_proto_init()
	file_proto_quorumpb_wal_proto_init()
	file_proto_quorumpb_rpc_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_RequestVote)(nil),
		(*Envelope_RequestVoteReply)(nil),
		(*Envelope_AppendEntries)(nil),
		(*Envelope_AppendEntriesReply)(nil),
		(*Envelope_InstallSnapshot)(nil),
		(*Envelope_InstallSnapshotReply)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quorumpb_rpc_proto_rawDesc), len(file_proto_quorumpb_rpc_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_quorumpb_rpc_proto_goTypes,
		DependencyIndexes: file_proto_quorumpb_rpc_proto_depIdxs,
		EnumInfos:         file_proto_quorumpb_rpc_proto_enumTypes,
		MessageInfos:      file_proto_quorumpb_rpc_proto_msgTypes,
	}.Build()
	File_proto_quorumpb_rpc_proto = out.File
	file_proto_quorumpb_rpc_proto_goTypes = nil
	file_proto_quorumpb_rpc_proto_depIdxs = nil
}
