// Wire protocol: raft message envelopes between peers, and the client-facing
// KV + status services.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/quorumpb/rpc.proto

package quorumpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaftTransport_Deliver_FullMethodName = "/quorumpb.RaftTransport/Deliver"
)

// RaftTransportClient is the client API for RaftTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaftTransportClient interface {
	// Deliver is a one-way stream of envelopes from one peer.
	Deliver(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Envelope, DeliverAck], error)
}

type raftTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewRaftTransportClient(cc grpc.ClientConnInterface) RaftTransportClient {
	return &raftTransportClient{cc}
}

func (c *raftTransportClient) Deliver(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Envelope, DeliverAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RaftTransport_ServiceDesc.Streams[0], RaftTransport_Deliver_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Envelope, DeliverAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransport_DeliverClient = grpc.ClientStreamingClient[Envelope, DeliverAck]

// RaftTransportServer is the server API for RaftTransport service.
// All implementations must embed UnimplementedRaftTransportServer
// for forward compatibility.
type RaftTransportServer interface {
	// Deliver is a one-way stream of envelopes from one peer.
	Deliver(grpc.ClientStreamingServer[Envelope, DeliverAck]) error
	mustEmbedUnimplementedRaftTransportServer()
}

// UnimplementedRaftTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaftTransportServer struct{}

func (UnimplementedRaftTransportServer) Deliver(grpc.ClientStreamingServer[Envelope, DeliverAck]) error {
	return status.Error(codes.Unimplemented, "method Deliver not implemented")
}
func (UnimplementedRaftTransportServer) mustEmbedUnimplementedRaftTransportServer() {}
func (UnimplementedRaftTransportServer) testEmbeddedByValue()                       {}

// UnsafeRaftTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaftTransportServer will
// result in compilation errors.
type UnsafeRaftTransportServer interface {
	mustEmbedUnimplementedRaftTransportServer()
}

func RegisterRaftTransportServer(s grpc.ServiceRegistrar, srv RaftTransportServer) {
	// If the following call panics, it indicates UnimplementedRaftTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaftTransport_ServiceDesc, srv)
}

func _RaftTransport_Deliver_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RaftTransportServer).Deliver(&grpc.GenericServerStream[Envelope, DeliverAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RaftTransport_DeliverServer = grpc.ClientStreamingServer[Envelope, DeliverAck]

// RaftTransport_ServiceDesc is the grpc.ServiceDesc for RaftTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaftTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quorumpb.RaftTransport",
	HandlerType: (*RaftTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Deliver",
			Handler:       _RaftTransport_Deliver_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/quorumpb/rpc.proto",
}

const (
	QuorumKV_Do_FullMethodName     = "/quorumpb.QuorumKV/Do"
	QuorumKV_Status_FullMethodName = "/quorumpb.QuorumKV/Status"
)

// QuorumKVClient is the client API for QuorumKV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuorumKVClient interface {
	Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoReply, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error)
}

type quorumKVClient struct {
	cc grpc.ClientConnInterface
}

func NewQuorumKVClient(cc grpc.ClientConnInterface) QuorumKVClient {
	return &quorumKVClient{cc}
}

func (c *quorumKVClient) Do(ctx context.Context, in *DoRequest, opts ...grpc.CallOption) (*DoReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoReply)
	err := c.cc.Invoke(ctx, QuorumKV_Do_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quorumKVClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusReply)
	err := c.cc.Invoke(ctx, QuorumKV_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuorumKVServer is the server API for QuorumKV service.
// All implementations must embed UnimplementedQuorumKVServer
// for forward compatibility.
type QuorumKVServer interface {
	Do(context.Context, *DoRequest) (*DoReply, error)
	Status(context.Context, *StatusRequest) (*StatusReply, error)
	mustEmbedUnimplementedQuorumKVServer()
}

// UnimplementedQuorumKVServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuorumKVServer struct{}

func (UnimplementedQuorumKVServer) Do(context.Context, *DoRequest) (*DoReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Do not implemented")
}
func (UnimplementedQuorumKVServer) Status(context.Context, *StatusRequest) (*StatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedQuorumKVServer) mustEmbedUnimplementedQuorumKVServer() {}
func (UnimplementedQuorumKVServer) testEmbeddedByValue()                  {}

// UnsafeQuorumKVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuorumKVServer will
// result in compilation errors.
type UnsafeQuorumKVServer interface {
	mustEmbedUnimplementedQuorumKVServer()
}

func RegisterQuorumKVServer(s grpc.ServiceRegistrar, srv QuorumKVServer) {
	// If the following call panics, it indicates UnimplementedQuorumKVServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuorumKV_ServiceDesc, srv)
}

func _QuorumKV_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuorumKVServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuorumKV_Do_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuorumKVServer).Do(ctx, req.(*DoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuorumKV_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuorumKVServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuorumKV_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuorumKVServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuorumKV_ServiceDesc is the grpc.ServiceDesc for QuorumKV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuorumKV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quorumpb.QuorumKV",
	HandlerType: (*QuorumKVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _QuorumKV_Do_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _QuorumKV_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/quorumpb/rpc.proto",
}
