// WAL record payloads. The wire format around them is
// [len:u32][crc32c:u32][payload]; see storage/wal.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/quorumpb/wal.proto

package quorumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_proto_quorumpb_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_wal_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Entry) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// WalRecord is one framed record in a WAL segment.
type WalRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Rec:
	//
	//	*WalRecord_HardState
	//	*WalRecord_Entries
	//	*WalRecord_Truncate
	Rec           isWalRecord_Rec `protobuf_oneof:"rec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_proto_quorumpb_wal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_wal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_wal_proto_rawDescGZIP(), []int{1}
}

func (x *WalRecord) GetRec() isWalRecord_Rec {
	if x != nil {
		return x.Rec
	}
	return nil
}

func (x *WalRecord) GetHardState() *HardStateRec {
	if x != nil {
		if x, ok := x.Rec.(*WalRecord_HardState); ok {
			return x.HardState
		}
	}
	return nil
}

func (x *WalRecord) GetEntries() *EntriesRec {
	if x != nil {
		if x, ok := x.Rec.(*WalRecord_Entries); ok {
			return x.Entries
		}
	}
	return nil
}

func (x *WalRecord) GetTruncate() *TruncateRec {
	if x != nil {
		if x, ok := x.Rec.(*WalRecord_Truncate); ok {
			return x.Truncate
		}
	}
	return nil
}

type isWalRecord_Rec interface {
	isWalRecord_Rec()
}

type WalRecord_HardState struct {
	HardState *HardStateRec `protobuf:"bytes,1,opt,name=hard_state,json=hardState,proto3,oneof"`
}

type WalRecord_Entries struct {
	Entries *EntriesRec `protobuf:"bytes,2,opt,name=entries,proto3,oneof"`
}

type WalRecord_Truncate struct {
	Truncate *TruncateRec `protobuf:"bytes,3,opt,name=truncate,proto3,oneof"`
}

func (*WalRecord_HardState) isWalRecord_Rec() {}

func (*WalRecord_Entries) isWalRecord_Rec() {}

func (*WalRecord_Truncate) isWalRecord_Rec() {}

type HardStateRec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          uint64                 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VotedFor      uint64                 `protobuf:"varint,2,opt,name=voted_for,json=votedFor,proto3" json:"voted_for,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HardStateRec) Reset() {
	*x = HardStateRec{}
	mi := &file_proto_quorumpb_wal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HardStateRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HardStateRec) ProtoMessage() {}

func (x *HardStateRec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_wal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HardStateRec.ProtoReflect.Descriptor instead.
func (*HardStateRec) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_wal_proto_rawDescGZIP(), []int{2}
}

func (x *HardStateRec) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HardStateRec) GetVotedFor() uint64 {
	if x != nil {
		return x.VotedFor
	}
	return 0
}

type EntriesRec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntriesRec) Reset() {
	*x = EntriesRec{}
	mi := &file_proto_quorumpb_wal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntriesRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntriesRec) ProtoMessage() {}

func (x *EntriesRec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_wal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntriesRec.ProtoReflect.Descriptor instead.
func (*EntriesRec) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_wal_proto_rawDescGZIP(), []int{3}
}

func (x *EntriesRec) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// TruncateRec logs the discard of entries at index >= from_index. An
// append-only file cannot physically delete a conflicting suffix, so
// truncation is itself a logged event that recovery replays — without it a
// restart resurrects entries the node already disowned to its leader.
type TruncateRec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromIndex     uint64                 `protobuf:"varint,1,opt,name=from_index,json=fromIndex,proto3" json:"from_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRec) Reset() {
	*x = TruncateRec{}
	mi := &file_proto_quorumpb_wal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRec) ProtoMessage() {}

func (x *TruncateRec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_wal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRec.ProtoReflect.Descriptor instead.
func (*TruncateRec) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_wal_proto_rawDescGZIP(), []int{4}
}

func (x *TruncateRec) GetFromIndex() uint64 {
	if x != nil {
		return x.FromIndex
	}
	return 0
}

// SnapshotFile is the on-disk snapshot (snap-<index>-<term>.db), framed
// [len:u32][crc32c:u32][payload] like WAL records.
type SnapshotFile struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastIncludedIndex uint64                 `protobuf:"varint,1,opt,name=last_included_index,json=lastIncludedIndex,proto3" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64                 `protobuf:"varint,2,opt,name=last_included_term,json=lastIncludedTerm,proto3" json:"last_included_term,omitempty"`
	Kv                []byte                 `protobuf:"bytes,3,opt,name=kv,proto3" json:"kv,omitempty"` // marshaled KVSnapshot
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SnapshotFile) Reset() {
	*x = SnapshotFile{}
	mi := &file_proto_quorumpb_wal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotFile) ProtoMessage() {}

func (x *SnapshotFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_quorumpb_wal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotFile.ProtoReflect.Descriptor instead.
func (*SnapshotFile) Descriptor() ([]byte, []int) {
	return file_proto_quorumpb_wal_proto_rawDescGZIP(), []int{5}
}

func (x *SnapshotFile) GetLastIncludedIndex() uint64 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *SnapshotFile) GetLastIncludedTerm() uint64 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *SnapshotFile) GetKv() []byte {
	if x != nil {
		return x.Kv
	}
	return nil
}

var File_proto_quorumpb_wal_proto protoreflect.FileDescriptor

const file_proto_quorumpb_wal_proto_rawDesc = "" +
	"\n" +
	"\x18proto/quorumpb/wal.proto\x12\bquorumpb\"E\n" +
	"\x05Entry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"\xb2\x01\n" +
	"\tWalRecord\x127\n" +
	"\n" +
	"hard_state\x18\x01 \x01(\v2\x16.quorumpb.HardStateRecH\x00R\thardState\x120\n" +
	"\aentries\x18\x02 \x01(\v2\x14.quorumpb.EntriesRecH\x00R\aentries\x123\n" +
	"\btruncate\x18\x03 \x01(\v2\x15.quorumpb.TruncateRecH\x00R\btruncateB\x05\n" +
	"\x03rec\"?\n" +
	"\fHardStateRec\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x04R\x04term\x12\x1b\n" +
	"\tvoted_for\x18\x02 \x01(\x04R\bvotedFor\"7\n" +
	"\n" +
	"EntriesRec\x12)\n" +
	"\aentries\x18\x01 \x03(\v2\x0f.quorumpb.EntryR\aentries\",\n" +
	"\vTruncateRec\x12\x1d\n" +
	"\n" +
	"from_index\x18\x01 \x01(\x04R\tfromIndex\"|\n" +
	"\fSnapshotFile\x12.\n" +
	"\x13last_included_index\x18\x01 \x01(\x04R\x11lastIncludedIndex\x12,\n" +
	"\x12last_included_term\x18\x02 \x01(\x04R\x10lastIncludedTerm\x12\x0e\n" +
	"\x02kv\x18\x03 \x01(\fR\x02kvB-Z+github.com/Dario-Zela/quorum/proto/quorumpbb\x06proto3"

var (
	file_proto_quorumpb_wal_proto_rawDescOnce sync.Once
	file_proto_quorumpb_wal_proto_rawDescData []byte
)

func file_proto_quorumpb_wal_proto_rawDescGZIP() []byte {
	file_proto_quorumpb_wal_proto_rawDescOnce.Do(func() {
		file_proto_quorumpb_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_quorumpb_wal_proto_rawDesc), len(file_proto_quorumpb_wal_proto_rawDesc)))
	})
	return file_proto_quorumpb_wal_proto_rawDescData
}

var file_proto_quorumpb_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_quorumpb_wal_proto_goTypes = []any{
	(*Entry)(nil),        // 0: quorumpb.Entry
	(*WalRecord)(nil),    // 1: quorumpb.WalRecord
	(*HardStateRec)(nil), // 2: quorumpb.HardStateRec
	(*EntriesRec)(nil),   // 3: quorumpb.EntriesRec
	(*TruncateRec)(nil),  // 4: quorumpb.TruncateRec
	(*SnapshotFile)(nil), // 5: quorumpb.SnapshotFile
}
var file_proto_quorumpb_wal_proto_depIdxs = []int32{
	2, // 0: quorumpb.WalRecord.hard_state:type_name -> quorumpb.HardStateRec
	3, // 1: quorumpb.WalRecord.entries:type_name -> quorumpb.EntriesRec
	4, // 2: quorumpb.WalRecord.truncate:type_name -> quorumpb.TruncateRec
	0, // 3: quorumpb.EntriesRec.entries:type_name -> quorumpb.Entry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_quorumpb_wal_proto_init() }
func file_proto_quorumpb_wal_proto_init() {
	if File_proto_quorumpb_wal_proto != nil {
		return
	}
	file_proto_quorumpb_wal_proto_msgTypes[1].OneofWrappers = []any{
		(*WalRecord_HardState)(nil),
		(*WalRecord_Entries)(nil),
		(*WalRecord_Truncate)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_quorumpb_wal_proto_rawDesc), len(file_proto_quorumpb_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_quorumpb_wal_proto_goTypes,
		DependencyIndexes: file_proto_quorumpb_wal_proto_depIdxs,
		MessageInfos:      file_proto_quorumpb_wal_proto_msgTypes,
	}.Build()
	File_proto_quorumpb_wal_proto = out.File
	file_proto_quorumpb_wal_proto_goTypes = nil
	file_proto_quorumpb_wal_proto_depIdxs = nil
}
